[project]
name = "trading-enhance-software"
version = "0.1.0"
description = "This software has the ambition to become a game changer in automatic trading"
authors = [
    { name = "guillaume poidatz", email = "79081686+guillaumePoidatz@users.noreply.github.com" }
]
license = { text = "GPL-3.0" }
readme = "README.md"
requires-python = ">=3.11,<=3.12"
dependencies = [
    "PyQt5 >=5.15.11,<6.0.0",
    "ccxt >=4.4.91,<5.0.0",
    "mplcursors",
    "ta",
    "fsspec",
    "pytest",
    "google-cloud-aiplatform",
    "google-cloud-storage",
    "google-auth",
    "rl-finance-framework @ git+https://github.com/guillaumePoidatz/rl-finance-framework.git@CH-00001-create-the-package"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
